# See https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: main
  repo: danielmoessner/recyclist.de

# See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

# See https://www.netlifycms.org/docs/configuration-options/#locale
locale: de

# See https://www.netlifycms.org/docs/configuration-options/#display-url
display_url: https://recyclist.de

# See https://www.netlifycms.org/docs/configuration-options/#site-url
site_url: https://recyclist.de

# See https://www.netlifycms.org/docs/configuration-options/#media-folder
media_folder: /content/media

# See https://www.netlifycms.org/docs/configuration-options/#public-folder
public_folder: ../media

# See https://www.netlifycms.org/docs/collection-types/
collections:
  - name: page
    label: Seiten
    label_singular: Seite
    delete: false
    editor:
      preview: false
    files:
      - file: content/pages/home.md
        label: Startseite
        name: home
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: home }
          - label: 'Meta'
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Titel, name: title, widget: string }
              - label: Beschreibung
                name: description
                widget: text
              - { label: Bild, name: image, widget: image }

  - name: bike
    label: Fahräder
    label_singular: Fahrrad
    editor:
      preview: true
    folder: content/bikes
    slug: '{{fields.slug}}'
    create: true
    preview_path: bikes/{{fields.slug}}
    fields:
      - { label: Sammlung, name: collection, widget: hidden, default: bike }
      - { label: Titel, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - label: 'Kategorie'
        name: 'category'
        widget: 'relation'
        collection: 'category'
        searchFields: ['title']
        valueField: 'title'
      - { label: Bild, name: image, widget: image }
      - { label: Preis, name: price, widget: number }
      - label: Größe
        name: size
        widget: select
        options:
          - { label: S, value: small }
          - { label: M, value: medium }
          - { label: L, value: large }
      - { label: Eckdaten, name: information, widget: text }

  - name: category
    label: Kategorien
    label_singular: Kategorie
    editor:
      preview: false
    folder: content/categories
    slug: '{{ fields.slug }}'
    create: true
    fields:
      - { label: Sammlung, name: collection, widget: hidden, default: category }
      - { label: Titel, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }

  - name: review
    label: Kundenrezensionen
    label_singular: Kundenrezension
    editor:
      preview: true
    folder: content/reviews
    slug: '{{ fields.slug }}'
    create: true
    fields:
      - { label: Sammlung, name: collection, widget: hidden, default: review }
      - { label: Titel, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Rezension, name: review, widget: text }

  - name: 'setting'
    label: Einstellungen
    label_singular: Einstellung
    delete: false
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: Global
        name: 'global-settings'
        preview: false
        fields:
          - { label: URL der Seite, name: siteUrl, widget: string, required: false }
          - { label: Favicon, name: favicon, widget: image }
          - { label: Telefon, name: phone, widget: string }
          - { label: Adresse, name: address, widget: text }
      - file: 'content/settings/navigation.yml'
        label: Navigation
        name: navigation-settings
        preview: false
        fields:
          - { label: Link 1 Name, name: link1, widget: string }
          - { label: Link 2 Name, name: link2, widget: string }
          - { label: Link 3 Name, name: link3, widget: string }
          - { label: Link 4 Name, name: link4, widget: string }
          - { label: Link 5 Name, name: link5, widget: string }
          - { label: Link 6 Name, name: link6, widget: string }
          - { label: Telefon Label, name: phoneLabel, widget: string }
          - { label: Adresse Label, name: addressLabel, widget: string }
